- name: "SCORED | 2.1.1 | HARDENING | Ensure chargen services are not enabled | chargen-dgram"
  stat:
      path: /etc/xinetd.d/chargen-dgram
  register: chargen_dgram_service
  tags:
      - level1
      - scored
      - services
      - patch
      - rule_2.1.1

- name: "SCORED | 2.1.1 | HARDENING | Ensure chargen services are not enabled | chargen-dgram"
  command: chkconfig chargen-dgram off
  notify: restart xinetd
  when: chargen_dgram_service.stat.exists
  tags:
      - level1
      - scored
      - services
      - patch
      - rule_2.1.1

- name: "SCORED | 2.1.1 | HARDENING | Ensure chargen services are not enabled | chargen-stream"
  stat:
      path: /etc/xinetd.d/chargen-stream
  register: chargen_stream_service
  tags:
      - level1
      - scored
      - services
      - patch
      - rule_2.1.1

- name: "SCORED | 2.1.1 | HARDENING | Ensure chargen services are not enabled | chargen-stream"
  command: chkconfig chargen-stream off
  notify: restart xinetd
  when: chargen_stream_service.stat.exists
  tags:
      - level1
      - scored
      - services
      - patch
      - rule_2.1.1

- name: "SCORED | 2.1.2 | HARDENING | Ensure daytime services are not enabled | daytime-dgram"
  stat:
      path: /etc/xinetd.d/daytime-dgram
  register: daytime_dgram_service
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.2

- name: "SCORED | 2.1.2 | HARDENING | Ensure daytime services are not enabled | daytime-dgram"
  command: chkconfig daytime-dgram off
  notify: restart xinetd
  when: daytime_dgram_service.stat.exists
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.2

- name: "SCORED | 2.1.2 | HARDENING | Ensure daytime services are not enabled | daytime-stream"
  stat:
      path: /etc/xinetd.d/daytime-stream
  register: daytime_stream_service
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.2

- name: "SCORED | 2.1.2 | HARDENING | Ensure daytime services are not enabled | daytime-stream"
  command: chkconfig daytime-stream off
  notify: restart xinetd
  when: daytime_stream_service.stat.exists
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.2

- name: "SCORED | 2.1.3 | HARDENING | Ensure discard services are not enabled | discard-dgram"
  stat:
      path: /etc/xinetd.d/discard-dgram
  register: discard_dgram_service
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.3

- name: "SCORED | 2.1.3 | HARDENING | Ensure discard services are not enabled | discard-dgram"
  command: chkconfig discard-dgram off
  notify: restart xinetd
  when: discard_dgram_service.stat.exists
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.3

- name: "SCORED | 2.1.3 | HARDENING | Ensure discard services are not enabled | discard-stream"
  stat:
      path: /etc/xinetd.d/discard-stream
  register: discard_stream_service
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.3

- name: "SCORED | 2.1.3 | HARDENING | Ensure discard services are not enabled | discard-stream"
  command: chkconfig discard-stream off
  notify: restart xinetd
  when: discard_stream_service.stat.exists
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.3

- name: "SCORED | 2.1.4 | HARDENING | Ensure echo services are not enabled | echo-dgram"
  stat:
      path: /etc/xinetd.d/echo-dgram
  register: echo_dgram_service
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.4

- name: "SCORED | 2.1.4 | HARDENING | Ensure echo services are not enabled | echo-dgram"
  command: chkconfig echo-dgram off
  notify: restart xinetd
  when: echo_dgram_service.stat.exists
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.4

- name: "SCORED | 2.1.4 | HARDENING | Ensure echo services are not enabled | echo-stream"
  stat:
      path: /etc/xinetd.d/echo-stream
  register: echo_stream_service
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.4

- name: "SCORED | 2.1.4 | HARDENING | Ensure echo services are not enabled | echo-stream"
  command: chkconfig echo-stream off
  notify: restart xinetd
  when: echo_stream_service.stat.exists
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.4

- name: "SCORED | 2.1.5 | HARDENING | Ensure time services are not enabled | time-dgram"
  stat:
      path: /etc/xinetd.d/time-dgram
  register: time_dgram_service
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.5

- name: "SCORED | 2.1.5 | HARDENING | Ensure time services are not enabled | time-dgram"
  command: chkconfig time-dgram off
  notify: restart xinetd
  when: time_dgram_service.stat.exists
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.5

- name: "SCORED | 2.1.5 | HARDENING | Ensure time services are not enabled | time-stream"
  stat:
      path: /etc/xinetd.d/time-stream
  register: time_stream_service
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.5

- name: "SCORED | 2.1.5 | HARDENING | Ensure time services are not enabled | time-stream"
  command: chkconfig time-stream off
  notify: restart xinetd
  when: time_stream_service.stat.exists
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.5

- name: "SCORED | 2.1.6 | HARDENING | Ensure tftp server is not enabled"
  stat:
      path: /etc/xinetd.d/tftp
  register: tftp_service
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.6

- name: "SCORED | 2.1.6 | HARDENING | Ensure tftp server is not enabled"
  command: chkconfig tftp off
  notify: restart xinetd
  when: tftp_service.stat.exists and rhel7cis_tftp_server == false
  tags:
      - level1
      - scored
      - patch
      - rule_2.1.6

- name: "SCORED | 2.1.7 | HARDENING | Ensure xinetd is not enabled"
  service:
      name: xinetd
      state: stopped
      enabled: no
  when: 
      - xinetd_service_status.stdout == "loaded" and not rhel7cis_xinetd_required
  tags:
      - level1
      - patch
      - scored
      - rule_2.1.7

- name: "NOTSCORED | 2.2.1.1 | HARDENING | Ensure time synchronization is in use - service install"
  yum:
      name: "{{ rhel7cis_time_synchronization }}"
      state: present
  tags:
      - level1
      - patch
      - rule_2.2.1.1

- name: "NOTSCORED | 2.2.1.1 | HARDENING | Ensure time synchronization is in use - service start"
  service:
      name: "{{ rhel7cis_time_synchronization }}d"
      state: started
      enabled: yes
  tags:
      - level1
      - patch
      - rule_2.2.1.1

- name: "NOTSCORED | 2.2.1.1 | HARDENING | Ensure time synchronization is in use - service stop ntp"
  service:
      name: ntpd
      state: stopped
      enabled: no
  when: rhel7cis_time_synchronization == "chrony" and ntpd_service_status.stdout == "loaded"
  tags:
      - level1
      - patch
      - rule_2.2.1.1

- name: "NOTSCORED | 2.2.1.1 | HARDENING | Ensure time synchronization is in use - service stop chrony"
  service:
      name: chronyd
      state: stopped
      enabled: no
  ignore_errors: yes
  when: rhel7cis_time_synchronization == "ntp" and chronyd_service_status.stdout == "loaded"
  tags:
      - level1
      - patch
      - rule_2.2.1.1

- name: "SCORED | 2.2.1.2 | HARDENING | Ensure ntp is configured | modify /etc/ntp.conf"
  template:
      src: ntp.conf.j2
      dest: /etc/ntp.conf
      owner: root
      group: root
      mode: 0644
  when: rhel7cis_time_synchronization == "ntp"
  tags:
      - level1
      - patch
      - rule_2.2.1.2

- name: "SCORED | 2.2.1.2 | HARDENING | Ensure ntp is configured | modify /etc/sysconfig/ntpd"
  lineinfile:
      dest: /etc/sysconfig/ntpd
      regexp: "^(#)?OPTIONS"
      line: "OPTIONS=\"-u ntp:ntp\""
  when: rhel7cis_time_synchronization == "ntp"
  tags:
      - level1
      - patch
      - rule_2.2.1.2

- name: "SCORED | 2.2.1.2 | HARDENING | Ensure ntp is configured | modify /usr/lib/systemd/system/ntpd.service"
  lineinfile:
      dest: /usr/lib/systemd/system/ntpd.service
      regexp: "^(#)?ExecStart"
      line: "ExecStart=/usr/sbin/ntpd -u ntp:ntp $OPTIONS"
  when: rhel7cis_time_synchronization == "ntp"
  tags:
      - level1
      - patch
      - rule_2.2.1.2

- name: "SCORED | 2.2.1.3 | HARDENING | Ensure chrony is configured"
  template:
      src: chrony.conf.j2
      dest: /etc/chrony.conf
      owner: root
      group: root
      mode: 0644
  when: rhel7cis_time_synchronization == "chrony"
  tags:
      - level1
      - patch
      - rule_2.2.1.3

- name: "SCORED | 2.2.1.3 | HARDENING | Ensure chrony is configured | modify /etc/sysconfig/chronyd | 1"
  lineinfile:
      dest: /etc/sysconfig/chronyd
      regexp: "^(#)?OPTIONS"
      line: "OPTIONS=\"-u chrony\""
      state: present
      create: yes
  when: rhel7cis_time_synchronization == "chrony"
  tags:
      - level1
      - patch
      - rule_2.2.1.3

- name: "SCORED | 2.2.2 | HARDENING | Ensure X Window System is not installed"
  yum:
      name: "{{item}}"
      state: absent
  when: not rhel7cis_xwindows_required
  with_items:
      - "@X Window System"
      - "xorg-x11*"
  tags:
      - level1
      - scored
      - xwindows
      - patch
      - rule_2.2.2

- name: "SCORED | 2.2.3 | HARDENING | Ensure Avahi Server is not enabled"
  service:
      name: avahi-daemon
      state: stopped
      enabled: no
  when: rhel7cis_avahi_server == false and avahi_service_status.stdout == "loaded"
  tags:
      - level1
      - scored
      - avahi
      - services
      - patch
      - rule_2.2.3

- name: "SCORED | 2.2.4 | HARDENING | Ensure CUPS is not enabled"
  service:
      name: cups
      state: stopped
      enabled: no
  when: rhel7cis_cups_server == false and cups_service_status.stdout == "loaded"
  tags:
      - level1
      - scored
      - cups
      - services
      - patch
      - rule_2.2.4

- name: "SCORED | 2.2.5 | HARDENING | Ensure DHCP Server is not enabled"
  service:
      name: dhcpd
      state: stopped
      enabled: no
  when: rhel7cis_dhcp_server == false and dhcpd_service_status.stdout == "loaded"
  tags:
      - level1
      - scored
      - dhcp
      - services
      - patch
      - rule_2.2.5

- name: "SCORED | 2.2.6 | HARDENING | Ensure LDAP server is not enabled"
  service:
      name: slapd
      state: stopped
      enabled: no
  when: rhel7cis_ldap_server == false and slapd_service_status.stdout == "loaded"
  tags:
      - level1
      - scored
      - ldap
      - services
      - patch
      - rule_2.2.6

- name: "SCORED | 2.2.7 | HARDENING | Ensure NFS and RPC are not enabled"
  service:
      name: nfs
      state: stopped
      enabled: no
  when: rhel7cis_nfs_rpc_server == false and nfs_service_status.stdout == "loaded"
  tags:
      - level1
      - scored
      - nfs
      - rpc
      - services
      - patch
      - rule_2.2.7

- name: "SCORED | 2.2.7 | HARDENING | Ensure NFS and RPC are not enabled"
  service:
      name: rpcbind
      state: stopped
      enabled: no
  when: rhel7cis_nfs_rpc_server == false and rpcbind_service_status.stdout == "loaded"
  tags:
      - level1
      - scored
      - nfs
      - rpc
      - services
      - patch
      - rule_2.2.7

- name: "SCORED | 2.2.8 | HARDENING | Ensure DNS Server is not enabled"
  service:
      name: named
      state: stopped
      enabled: no
  when: rhel7cis_named_server == false and named_service_status.stdout == "loaded"
  tags:
      - level1
      - patch
      - rule_2.2.8

- name: "SCORED | 2.2.9 | HARDENING | Ensure FTP Server is not enabled"
  service:
      name: vsftpd
      state: stopped
      enabled: no
  when: rhel7cis_vsftpd_server == false and vsftpd_service_status.stdout == "loaded"
  tags:
      - level1
      - patch
      - rule_2.2.9

- name: "SCORED | 2.2.10 | HARDENING | Ensure HTTP server is not enabled"
  service:
      name: httpd
      state: stopped
      enabled: no
  when: rhel7cis_httpd_server == false and httpd_service_status.stdout == "loaded"
  tags:
      - level1
      - patch
      - rule_2.2.10

- name: "SCORED | 2.2.11 | HARDENING | Ensure IMAP and POP3 server is not enabled"
  service:
      name: dovecot
      state: stopped
      enabled: no
  when: rhel7cis_dovecot_server == false and dovecot_service_status.stdout == "loaded"
  tags:
      - level1
      - patch
      - rule_2.2.11

- name: "SCORED | 2.2.12 | HARDENING | Ensure Samba is not enabled"
  service:
      name: smb
      state: stopped
      enabled: no
  when: rhel7cis_smb_server == false and smb_service_status.stdout == "loaded"
  tags:
      - level1
      - patch
      - rule_2.2.12

- name: "SCORED | 2.2.13 | HARDENING | Ensure HTTP Proxy Server is not enabled"
  service:
      name: squid
      state: stopped
      enabled: no
  when: rhel7cis_squid_server == false and squid_service_status.stdout == "loaded"
  tags:
      - level1
      - patch
      - rule_2.2.13

- name: "SCORED | 2.2.14 | HARDENING | Ensure SNMP Server is not enabled"
  service:
      name: snmpd
      state: stopped
      enabled: no
  when: rhel7cis_snmp_server == false and snmpd_service_status.stdout == "loaded"
  tags:
      - level1
      - patch
      - rule_2.2.14

- name: "SCORED | 2.2.15 | HARDENING | Ensure mail transfer agent is configured for local-only mode"
  lineinfile:
      dest: /etc/postfix/main.cf
      regexp: "^(#)?inet_interfaces"
      line: "inet_interfaces = localhost"
  when: rhel7cis_is_mail_server == false and postfix_installed.rc == 0
  tags:
      - level1
      - patch
      - rule_2.2.15

- name: "SCORED | 2.2.16 | HARDENING | Ensure NIS Server is not enabled"
  service:
      name: ypserv
      state: stopped
      enabled: no
  when: rhel7cis_nis_server == false and ypserv_service_status.stdout == "loaded"
  tags:
      - level1
      - patch
      - rule_2.2.16

- name: "SCORED | 2.2.17 | HARDENING | Ensure rsh server is not enabled | rsh"
  service:
      name: rsh.socket
      state: stopped
      enabled: no
  when: rhel7cis_rsh_server == false and rsh_service_status.stdout == "loaded"
  tags:
      - level1
      - patch
      - rule_2.2.17

- name: "SCORED | 2.2.17 | HARDENING | Ensure rsh server is not enabled | rlogin"
  service:
      name: rlogin.socket
      state: stopped
      enabled: no
  when: rhel7cis_rsh_server == false and rlogin_service_status.stdout == "loaded"
  tags:
      - level1
      - patch
      - rule_2.2.17

- name: "SCORED | 2.2.17 | HARDENING | Ensure rsh server is not enabled | rexec"
  service:
      name: rexec.socket
      state: stopped
      enabled: no
  when: rhel7cis_rsh_server == false and rexec_service_status.stdout == "loaded"
  tags:
      - level1
      - patch
      - rule_2.2.17

- name: "SCORED | 2.2.18 | HARDENING | Ensure telnet server is not enabled"
  service:
      name: telnet
      state: stopped
      enabled: no
  when: rhel7cis_telnet_server == false and telnet_service_status.stdout == "loaded"
  tags:
      - level1
      - patch
      - rule_2.2.18

- name: "SCORED | 2.2.19 | HARDENING | Ensure tftp server is not enabled"
  service:
      name: tftp
      state: stopped
      enabled: no
  when: rhel7cis_tftp_server == false and tftp_service_status.stdout == "loaded"
  tags:
      - level1
      - scored
      - insecure_services
      - tftp
      - patch
      - rule_2.2.19

- name: "SCORED | 2.2.20 | HARDENING | Ensure rsync service is not enabled "
  service:
      name: rsyncd
      state: stopped
      enabled: no
  when: rhel7cis_rsyncd_server == false and rsyncd_service_status.stdout == "loaded"
  tags:
      - level1
      - patch
      - rule_2.2.20

- name: "SCORED | 2.2.21 | HARDENING | Ensure talk server is not enabled"
  service:
      name: ntalk
      state: stopped
      enabled: no
  when: rhel7cis_ntalk_server == false and ntalk_service_status.stdout == "loaded"
  tags:
      - level1
      - patch
      - rule_2.2.21

- name: "SCORED | 2.3.1 | HARDENING | Ensure NIS Client is not installed"
  yum:
      name: ypbind
      state: absent
  when: rhel7cis_ypbind_required == false
  tags:
      - level1
      - patch
      - rule_2.3.1

- name: "SCORED | 2.3.2 | HARDENING | Ensure rsh client is not installed"
  yum:
      name: rsh
      state: absent
  when: rhel7cis_rsh_required == false
  tags:
      - level1
      - patch
      - rule_2.3.2

- name: "SCORED | 2.3.3 | HARDENING | Ensure talk client is not installed"
  yum:
      name: talk
      state: absent
  when: rhel7cis_talk_required == false
  tags:
      - level1
      - patch
      - rule_2.3.3

- name: "SCORED | 2.3.4 | HARDENING | Ensure telnet client is not installed"
  yum:
      name: telnet
      state: absent
  when: rhel7cis_telnet_required == false
  tags:
      - level1
      - patch
      - rule_2.3.4

- name: "SCORED | 2.3.5 | HARDENING | Ensure LDAP client is not installed"
  yum:
      name: openldap-clients
      state: absent
  when: rhel7cis_openldap_clients_required == false
  tags:
      - level1
      - patch
      - rule_2.3.5
